modLoader="javafml"
loaderVersion="[1,)"
license="MIT (code) — assets are All Rights Reserved"

[[mixins]]
config="chaoschunks.mixins.json"

[[mods]]
modId="chaoschunks"
version="${mod_version}"
displayName="ChaosChunks"
bannerFile="logo.png"
credits="Dermitio"
authors="Dermitio"
displayTest="IGNORE_SERVER_VERSION"
description="Randomize your chunks to your hearts content!"

[[dependencies.chaoschunks]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},26.4)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chaoschunks]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
