modLoader="javafml"
loaderVersion="[1,)"
license="MIT (code) — assets are All Rights Reserved"

[[mixins]]
config="chaoschunks.mixins.json"

[[mods]]
modId="chaoschunks"
version="0.3.1"
displayName="ChaosChunks"
logoFile="logo.png"
credits="Dermitio"
authors="Dermitio"
displayTest="IGNORE_SERVER_VERSION"
description="Randomize your chunks to your hearts content!"

[[dependencies.chaoschunks]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.*,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chaoschunks]]
    modId="minecraft"
    type="required"
    versionRange="[26.1,26.9)"
    ordering="NONE"
    side="BOTH"
