modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mixins]]
config="chaoschunks.mixins.json"

[[mods]]
modId="chaoschunks"
version="0.2.H3.F1 1.21.1"
displayName="ChaosChunks"
logoFile="logo.png"
credits="Dermitio"
authors="Dermitio"
description="Randomize your chunks to your hearts content!"

[[dependencies.chaoschunks]]
    modId="neoforge" 
    type="required" 
    versionRange="[21.1,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.chaoschunks]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.21.2)"
    ordering="NONE"
    side="BOTH"
